ARG BUILD_IMAGE=docker.io/rust:1.97
ARG RUNTIME_IMAGE=gcr.io/distroless/cc-debian13:nonroot

FROM --platform=$BUILDPLATFORM ${BUILD_IMAGE} AS dataflow-build

WORKDIR /build/rust/dataflow

ARG BUILDPLATFORM
ARG TARGETPLATFORM
ARG FEATURES
ARG BUILD_CACHE_SUFFIX=default
ARG RUSTFLAGS="-C target-cpu=native"

ENV FEATURES=${FEATURES}
ENV RUSTFLAGS=${RUSTFLAGS}

RUN apt-get update && apt-get install -y clang libclang-dev protobuf-compiler

COPY --from=otel-arrow /proto/opentelemetry/proto /build/proto/opentelemetry/proto
COPY --from=otel-arrow /proto/opentelemetry-proto /build/proto/opentelemetry-proto
COPY --from=otel-arrow /rust/experimental /build/rust/experimental
COPY --from=otel-arrow /THIRD_PARTY_NOTICES.txt /build/THIRD_PARTY_NOTICES.txt

COPY . /build/rust/dataflow/.

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,id=kafka-e2e-target-${BUILD_CACHE_SUFFIX},target=/build/rust/dataflow/target \
    sed -i 's/\r$//' cross-arch-build.sh && ./cross-arch-build.sh

FROM ${RUNTIME_IMAGE}

ARG RUNTIME_USER=nonroot

WORKDIR /home/nonroot
COPY --from=dataflow-build --chown=${RUNTIME_USER}:${RUNTIME_USER} /build/rust/dataflow/df_engine .

USER ${RUNTIME_USER}
ENTRYPOINT ["/home/nonroot/df_engine"]
