input {
  udp {
    port => 5516
    codec => plain {
      charset => "UTF-8"
    }
  }
}

output {
  kafka {
    bootstrap_servers => "kafka:9093"
    topic_id => "syslog-raw-logstash"
    client_id => "logstash-syslog-producer"
    security_protocol => "SASL_SSL"
    sasl_mechanism => "PLAIN"
    sasl_jaas_config => "org.apache.kafka.common.security.plain.PlainLoginModule required username='plain' password='plain-secret';"
    ssl_truststore_location => "/etc/kafka/certs/kafka.truststore.jks"
    ssl_truststore_password => "changeit"
    ssl_truststore_type => "JKS"
    codec => plain {
      format => "%{message}"
    }
  }
}
