input {
  udp {
    port => 5516
    tags => ["raw"]
    codec => plain {
      charset => "UTF-8"
    }
  }

  syslog {
    port => 5517
    tags => ["parsed"]
    ecs_compatibility => "disabled"
    grok_pattern => '<%{POSINT:priority}>%{NONNEGINT:version} %{TIMESTAMP_ISO8601:timestamp} %{NOTSPACE:logsource} %{NOTSPACE:program} %{NOTSPACE:pid} %{NOTSPACE:msgid} (?:-|(?<structured_data>(?:\[[^\]]*\])+)) %{GREEDYDATA:message}'
  }
}

output {
  if "raw" in [tags] {
    kafka {
      bootstrap_servers => "kafka:9093"
      topic_id => "syslog-raw-logstash"
      client_id => "logstash-raw-syslog-producer"
      security_protocol => "SASL_SSL"
      sasl_mechanism => "PLAIN"
      sasl_jaas_config => "org.apache.kafka.common.security.plain.PlainLoginModule required username='plain' password='plain-secret';"
      ssl_truststore_location => "/etc/kafka/certs/kafka.truststore.jks"
      ssl_truststore_password => "changeit"
      ssl_truststore_type => "JKS"
      codec => plain {
        format => "%{message}"
      }
    }
  } else if "parsed" in [tags] {
    kafka {
      bootstrap_servers => "kafka:9093"
      topic_id => "syslog-parsed-logstash"
      client_id => "logstash-parsed-syslog-producer"
      security_protocol => "SASL_SSL"
      sasl_mechanism => "PLAIN"
      sasl_jaas_config => "org.apache.kafka.common.security.plain.PlainLoginModule required username='plain' password='plain-secret';"
      ssl_truststore_location => "/etc/kafka/certs/kafka.truststore.jks"
      ssl_truststore_password => "changeit"
      ssl_truststore_type => "JKS"
      codec => json
    }
  }
}
