module(load="imudp")
module(load="omkafka")

template(name="RawSyslog" type="string" string="%rawmsg%")

ruleset(name="publishToKafka" queue.type="LinkedList") {
    action(
        type="omkafka"
        broker=["kafka:9093"]
        topic="syslog-raw"
        template="RawSyslog"
        confParam=[
            "security.protocol=SASL_SSL",
            "sasl.mechanisms=PLAIN",
            "sasl.username=plain",
            "sasl.password=plain-secret",
            "ssl.ca.location=/etc/kafka/certs/ca.crt"
        ]
    )
}

input(type="imudp" port="5515" ruleset="publishToKafka")
