BEGIN;

CREATE TABLE IF NOT EXISTS application_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    severity TEXT NOT NULL,
    message TEXT NOT NULL
);

TRUNCATE TABLE application_logs RESTART IDENTITY;

INSERT INTO application_logs (severity, message)
SELECT
    CASE
        WHEN record_number % 20 = 0 THEN 'ERROR'
        WHEN record_number % 5 = 0 THEN 'WARN'
        ELSE 'INFO'
    END,
    format('postgres test event %s', record_number)
FROM generate_series(1, 1000000) AS records(record_number);

COMMIT;
